# Generated by Django 6.0.2 on 2026-02-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('previous_close', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('fifty_day_average', models.FloatField(blank=True, null=True)),
                ('two_hundred_day_average', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('price_to_book', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('return_on_equity', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('dividend_rate', models.FloatField(blank=True, null=True)),
                ('payout_ratio', models.FloatField(blank=True, null=True)),
                ('five_year_avg_dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('enterprise_value', models.BigIntegerField(blank=True, null=True)),
                ('three_month_average_volume', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description_full', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='stock.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock Details',
            },
        ),
        migrations.CreateModel(
            name='StockHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='stock.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock Historical Data',
                'ordering': ['date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
